<a href="https://colab.research.google.com/github/kalyan-81/basics-of-python/blob/main/arrays_in_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **what is an array?**
An array is an  object that stores a group of elements(or values) if same data type.
* Array can store only one type of data. It means, only integer type or float type elements.
* Array cannot store one integer, one float, one character type elements into the same array.
* Arrays can increase or decrease their size dynamically. It means we need not to mention the size of an array.
* when an element is added to the array, it will increase it's size and when an element is removed it will reduces it's size.
* methods that are useful to process the elements of any array are available in 'array' module.

# difference between arrays and lists
* Arrays are similar to lists. But the main difference is that arrays can store only one type of elements. where as lists can store different types of elements.
* arrays use  less memory than lists.
* Arrays are faster execution than lists.



# In python, there is a standard module name **'array'** using this we can create and use arrays

# creating an Array
**syntax**
 arrayname=array(type code,[elements])
 

In [ ]:
import array
#type code 'b' for signed integer
a=array.array('i',[2,3,4,5,5,])# first array represents module name, second array represents class name
print(a)
print(type(a))

array('i', [2, 3, 4, 5, 5])
<class 'array.array'>


In [ ]:
import array as arr
#type code 'b' for signed integer
a=arr.array('i',[2,3,4,5,5,])
print(a)
print(type(a))

array('i', [2, 3, 4, 5, 5])
<class 'array.array'>


In [ ]:
from array import *
#type code 'b' for signed integer
a=array('i',[2,3,4,5,5,])# array represents class name
print(a)
print(type(a))

array('i', [2, 3, 4, 5, 5])
<class 'array.array'>



**b** -- signed integer, size=1\
**B** -- unsigned integer, size =1\
**i** --signed integer, size =2\
**I** --unsigned integer,  size=2\
**l** -- signed integer    size=4\
**L** -- unsigned integer  size=4\
**f** -- floating point   size =4\
**d** -- double precision floating point   size=8\
**u** -- unicode character    size=2


In [ ]:
from array import *
#type code 'b' for signed integer
a=array('u',['k','a','l','y','a','n'])# array represents class name
print(a)
print(type(a))

array('u', 'kalyan')
<class 'array.array'>


In [ ]:
for i in a:
  print(i)

k
a
l
y
a
n


In [ ]:
#creating one array from another array
from array import*
arr1=array('d',[1.5,2.5,-3.5])

#use the same typecode and muliply each element of arr1 with 3
arr2=array(arr1.typecode,(a*3 for a in arr1))

for i in arr2:
  print(i)

4.5
7.5
-10.5


# Indexing and slicing on Arrays


In [ ]:
x=array('i',[10,20,304,50])
print(len(x))
print(x[1:3])# slicing

4
array('i', [20, 304])


In [ ]:
y=x[2:4]# slicing
print(y)

array('i', [304, 50])


In [ ]:
x1=array('i',[1,2,3,4,5,6,7,8])
y=x1[2:7:2]
y

array('i', [3, 5, 7])

In [ ]:
#replace the elements of array with slicing
x1[1:3]=array('i',[9,10])
x1


array('i', [1, 9, 10, 4, 5, 6, 7, 8])

In [ ]:
#retrieving using range of elements using slicing and for loop
x2=array('i',[10,203,40,50,60,70,80,90])

for i in x2[4:6]:
  print(i)

60
70


# Array methods


#1. array.append(x):
adds an element x at the end of the existing array.

In [ ]:
from array import*
a=array('i',[1,2,3,4,1,2,3,3,4,3])
a.append(5)
a

array('i', [1, 2, 3, 4, 1, 2, 3, 3, 4, 3, 5])

#2.array.count(x):
returns the number of occurrences of element x in the array.

In [ ]:
a.count(1)

2

#3.array.extend():
appends x at the end of the array. 'x' can be another array or iterable object.

In [ ]:
a.extend([90,93,99])#iterable list
a

array('i', [1, 2, 3, 4, 1, 2, 3, 3, 4, 3, 5, 90, 93, 99])

In [ ]:
a.extend((22,23,24))# iterable tuple
a

array('i', [1, 2, 3, 4, 1, 2, 3, 3, 4, 3, 5, 90, 93, 99, 22, 23, 24])

In [ ]:
a.extend(45)
a

TypeError: ignored

#4.array.fromfile(f,n):
reads n items(in binary format) from the file object f and appends to the end of the array.'f' must be a file object. Raises' EOFError' if fewer than in items are read.

**this will be explained in files class**

#5.array.fromlist(lst):
Appends items from the lst to the end of the array. 'lst' can be any list or iterable object.


In [ ]:
from array import*
arr=array('i',[1,2,3,4,5])
arr.fromlist([6,7,8,9])
arr



array('i', [1, 2, 3, 4, 5, 6, 7, 8, 9])

#6.array.fromstring(s):
appends items from string 's' to the end of the array.

ValueError: ignored

#7.array.index(x):
returns the position number of the first occurrence of element x in the array.  Raises 'Value Error' if not found.

In [ ]:
from array import*
arr=array('i',[1,2,3,4,5])
arr.index(4)

3

#8.array.insert(index,element):
inserts the element at the index position in the existed array.


In [ ]:
from array import*
arr=array('i',[1,2,3,4,5])
arr.insert(0,100)# after insert remaining elements shifts to right
arr

array('i', [100, 1, 2, 3, 4, 5])

#9.array.pop(x):
removes the last item from the array. x is the index, by default it takes last index.

In [ ]:
from array import*
arr=array('i',[1,2,3,4,5])
arr.pop()

5

In [ ]:
arr

array('i', [1, 2, 3, 4])

In [ ]:
arr.pop(2)# 2 is the index
arr

array('i', [1, 2, 4])

#10 array.remove(x):
removes the first occurence of x in the array. Raises 'Value Error' if not found.



In [ ]:
from array import*
arr=array('i',[1,2,3,4,5,3,4,5])
arr.remove(3)
arr

array('i', [1, 2, 4, 5, 3, 4, 5])

#11. array.reverse()
reverses the order of the elements in an array.


In [ ]:
from array import*
arr=array('i',[1,2,3,4,5,3,4,5])
arr.reverse()
arr

array('i', [5, 4, 3, 5, 4, 3, 2, 1])

#12 array.tofile(f)
writes all elements to the file f.





In [ ]:
#example

#13 array.tolist()
converts the array into list


In [ ]:
from array import*
arr=array('i',[1,2,3,4,5,3,4,5])
arr.tolist()

[1, 2, 3, 4, 5, 3, 4, 5]

#14. array.tostring()
converts the array into a string.

In [ ]:
from array import*
arr=array('i',[1,2,3,4,5,3,4,5])
arr.tostring()

b'\x01\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x00\x04\x00\x00\x00\x05\x00\x00\x00\x03\x00\x00\x00\x04\x00\x00\x00\x05\x00\x00\x00'

In [ ]:
arr.typecode # returns the type code character used to create the array 

'i'

In [ ]:
arr.itemsize #returns size of the items stored in the array in bytes

4

# write python program to store the marks into array and find the total marks and average marks

In [ ]:
marks_list=[int(i) for i in input('enter the marks:').split()]
marks_list

enter the marks:10 20 30 40 50 60 70 80 90


[10, 20, 30, 40, 50, 60, 70, 80, 90]

In [ ]:
from array import*
arr=array('i',marks_list)
arr

array('i', [10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
sum=0
for i in arr:
  sum+=i

sum

450

In [ ]:
average=sum/len(arr)
average

50.0

#write the program to sort the array using bubble sort algorithm

In [ ]:
from array import *
x=array('i',[])
n=int(input('enter the number of elements:'))
for i in range(n):
  ele=int(input('enter the element'))
  x.append(ele)

print('original array',x)

enter the number of elements:10
enter the element9
enter the element8
enter the element7
enter the element7
enter the element5
enter the element4
enter the element6
enter the element3
enter the element2
enter the element1
original array array('i', [9, 8, 7, 7, 5, 4, 6, 3, 2, 1])


In [ ]:
#bubble sort code
x=array('i', [9, 8, 7, 7, 5, 4, 6, 3, 2, 1])
for i in range(n-1):
  for j in range(n-1-i):
    if x[j]>x[j+1]:
      x[j],x[j+1]=x[j+1],x[j] #swapping
    print('inner loop ',j,'iteration',x)
  print('---------------------------')
  print('outer loop',i,'iteration',x)
  

print('sorted array',x)


inner loop  0 iteration array('i', [8, 9, 7, 7, 5, 4, 6, 3, 2, 1])
inner loop  1 iteration array('i', [8, 7, 9, 7, 5, 4, 6, 3, 2, 1])
inner loop  2 iteration array('i', [8, 7, 7, 9, 5, 4, 6, 3, 2, 1])
inner loop  3 iteration array('i', [8, 7, 7, 5, 9, 4, 6, 3, 2, 1])
inner loop  4 iteration array('i', [8, 7, 7, 5, 4, 9, 6, 3, 2, 1])
inner loop  5 iteration array('i', [8, 7, 7, 5, 4, 6, 9, 3, 2, 1])
inner loop  6 iteration array('i', [8, 7, 7, 5, 4, 6, 3, 9, 2, 1])
inner loop  7 iteration array('i', [8, 7, 7, 5, 4, 6, 3, 2, 9, 1])
inner loop  8 iteration array('i', [8, 7, 7, 5, 4, 6, 3, 2, 1, 9])
---------------------------
outer loop 0 iteration array('i', [8, 7, 7, 5, 4, 6, 3, 2, 1, 9])
inner loop  0 iteration array('i', [7, 8, 7, 5, 4, 6, 3, 2, 1, 9])
inner loop  1 iteration array('i', [7, 7, 8, 5, 4, 6, 3, 2, 1, 9])
inner loop  2 iteration array('i', [7, 7, 5, 8, 4, 6, 3, 2, 1, 9])
inner loop  3 iteration array('i', [7, 7, 5, 4, 8, 6, 3, 2, 1, 9])
inner loop  4 iteration array('i', 

# write a program to search the position of number in array


In [ ]:
x=array('i', [9, 8, 7, 7, 5, 4, 6, 3, 2, 1])
#search for the posion of 4
for i in range(len(x)):
  if x[i]==4:
    print('find at position',i+1)


find at position 6


In [ ]:
#using index method
x=array('i', [9, 8, 7, 7, 5, 4, 6, 3, 2, 1])
#search for the posion of 4
pos=x.index(4)
print('find at position',pos+1)

find at position 6


# Types of Arrays
* single dimensional
* multi dimensional

In [ ]:
#example for single or one dimensional array
#marks of 5 subjects can be written as one dimensional array for one student
from array import*
marks=array('i',[50,56,78,97,55])
print(marks)
print(type(marks))


array('i', [50, 56, 78, 97, 55])
<class 'array.array'>


In [ ]:
#example for multi-dimensional array
#multi dimesional arrays are combination of one dimensional arrays
marks=array('i',[[20,30,40,50,60],
                 [90,80,70,60,50],
                 [86,67,53,56,45]]) #marks of 3 students
marks

TypeError: ignored

# Python does not support multidimensional arrays
# But we can construct multidimensional arrays using third party packages **Numpy**


In [ ]:
import numpy
arr=numpy.array([10,20,30,40,50,60])
print(arr)
print(type(arr))

[10 20 30 40 50 60]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
arr=np.array([10,20,30,40,50,60])
print(arr)
print(type(arr))

[10 20 30 40 50 60]
<class 'numpy.ndarray'>


In [ ]:
from numpy import *
arr=array([20,30,40,50,60])
print((arr))
print(type(arr))

[20 30 40 50 60]
<class 'numpy.ndarray'>


#creation of arrays using numpy functions
* using array() functions
* using linspace() functions
* using logspace() functions
* using arange() functions
* using zeros() and ones() functions 

# using array()

In [ ]:
# array()
from numpy import *
arr=array(['k','a','l','y','a','n'])
print(arr)

['k' 'a' 'l' 'y' 'a' 'n']


# using linspace()
the linspace() function is used to create an array with evenly spaced points between a starting point and ending point. 
* syntax\
linspace(start,stop,n)\
start...starting element\
stop....ending element\
n.....number of parts the elements should be divided


In [ ]:
#linspace()
from numpy import *
arr=linspace(0,10,5)
print(arr)

[ 0.   2.5  5.   7.5 10. ]


In [ ]:
#linspace()
from numpy import *
arr=linspace(0,100,5)
print(arr)

[  0.  25.  50.  75. 100.]


# using logspace()
produces evenly spaced points on a logarithmically spaced scale.

* syntax is similar to linspace()

In [ ]:
from numpy import*
arr=logspace(1,4,5) # this represent the values 10^1 to 10^4 and divided into 5 equal points and stored in arr
print(arr)

[   10.            56.23413252   316.22776602  1778.27941004
 10000.        ]


# using arange()
arange() function in numpy is same as range() function in python.

In [ ]:
from numpy import*
arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arange(5,10)

array([5, 6, 7, 8, 9])

In [ ]:
arange(1,10,3)

array([1, 4, 7])

In [ ]:
arange(10,0,-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [ ]:
#create an array with even numbers upto 10
from numpy import *
even=arange(2,11,2)
print(even)

[ 2  4  6  8 10]


In [ ]:
#create an array with odd numbers upto 20
from numpy import *
odd=arange(1,21,2)
print(odd)

[ 1  3  5  7  9 11 13 15 17 19]


# creating arrays using zeros() and ones() functions

zeros(n,datatype)\
ones(n,datatype)

In [ ]:
zeros(5) #default data type is float

array([0., 0., 0., 0., 0.])

In [ ]:
zeros(5,int) #integer data type

array([0, 0, 0, 0, 0])

In [ ]:
ones(5) #default data type is float

array([1., 1., 1., 1., 1.])

In [ ]:
ones(5,int) # integer data type

array([1, 1, 1, 1, 1])

# mathematical operations on arrays

In [ ]:
from numpy import*
arr=arange(0,11)
print(arr)
arr2=arr+5 # adding 5 to every element in an array
print(arr2)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 5  6  7  8  9 10 11 12 13 14 15]


In [ ]:
from numpy import*
arr1=arange(0,11,2)
print('arr1=',arr1)
arr2=arange(10,21,2)
print('arr2=',arr2)
print(arr1+arr2)
# NOTE: given two arrays should be in same size

arr1= [ 0  2  4  6  8 10]
arr2= [10 12 14 16 18 20]
[10 14 18 22 26 30]


In [ ]:
# thid program raises an error
from numpy import*
arr1=arange(0,11,2)
print('arr1=',arr1)
arr2=arange(10,21,1)
print('arr2=',arr2)
print(arr1+arr2)

arr1= [ 0  2  4  6  8 10]
arr2= [10 11 12 13 14 15 16 17 18 19 20]


ValueError: ignored

In [ ]:
from numpy import*
arr1=arange(0,11,2)
print('arr1=',arr1)
arr2=arange(10,21,2)
print('arr2=',arr2)
print(arr1/arr2)

arr1= [ 0  2  4  6  8 10]
arr2= [10 12 14 16 18 20]
[0.         0.16666667 0.28571429 0.375      0.44444444 0.5       ]


# These kinds of operations are called vectorized operations since the entire array(or vector) is processed just like a variable.

* vectorized operations are faster. Adding two arrays in the form of a+b is much faster than taking the corresponding elements of both the arrays and then adding them.
* vectorized operations are syntactically clearer. To add two arrays, we can simply write a+b. This is clear than using loops and iterating through all the elements of the arrays while  adding them.
* vectorized operations provide compact code.



# mathematical functions in numpy

In [ ]:
from numpy import *
arr=arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
sin(arr) # all elements in array taken as radians

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [ ]:
cos(arr)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029,  0.75390225, -0.14550003, -0.91113026, -0.83907153])

In [ ]:
tan(arr)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501,
       -0.29100619,  0.87144798, -6.79971146, -0.45231566,  0.64836083])

In [ ]:
arr1=arange(10,20,1.5)
arcsin(arr1)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in arcsin
  


array([nan, nan, nan, nan, nan, nan, nan])

In [ ]:
arccos(arr1)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in arccos
  """Entry point for launching an IPython kernel.


array([nan, nan, nan, nan, nan, nan, nan])

In [ ]:
arctan(arr1)

array([1.47112767, 1.48405799, 1.49402444, 1.50193984, 1.50837752,
       1.51371554, 1.51821327])

In [ ]:
log(arr1)

array([2.30258509, 2.44234704, 2.56494936, 2.67414865, 2.77258872,
       2.86220088, 2.94443898])

In [ ]:
abs(arr1)

array([10. , 11.5, 13. , 14.5, 16. , 17.5, 19. ])

In [ ]:
sqrt(arr1)

array([3.16227766, 3.39116499, 3.60555128, 3.80788655, 4.        ,
       4.18330013, 4.35889894])

In [ ]:
power(arr1,2)

array([100.  , 132.25, 169.  , 210.25, 256.  , 306.25, 361.  ])

In [ ]:
exp(arr1)

array([2.20264658e+04, 9.87157710e+04, 4.42413392e+05, 1.98275926e+06,
       8.88611052e+06, 3.98247844e+07, 1.78482301e+08])

In [ ]:
sum(arr1)

101.5

In [ ]:
prod(arr1)

115324300.0

In [ ]:
min(arr1)

10.0

In [ ]:
max(arr1)

19.0

In [ ]:
mean(arr1)

14.5

In [ ]:
median(arr1)

14.5

In [ ]:
var(arr)

0.014466666666666664

In [ ]:
cov(arr)

array(0.0217)

In [ ]:
std(arr)

0.12027745701779143

In [ ]:
argmin(arr1) # returns the index of the minimum value

0

In [ ]:
argmax(arr1) # return the index of max value

6

In [ ]:
arr=array([1,2,3,2,1,2,3,4,5,6,7,8,9])
unique((arr)) # returns the array that contains unique elements of arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
sort(arr)

array([1, 1, 2, 2, 2, 3, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr=array([1,2,3,4])
arr1=array([5,6,7,8])
concatenate([arr,arr1])

array([1, 2, 3, 4, 5, 6, 7, 8])

#Comparing arrays
 compares the corresponding elements of the arrays and return another array with boolean type values.

In [ ]:
from numpy import*
a=array([1,2,3,4])
b=array([0,2,3,1])
c=a==b
print('result of a==b',c)
c=a>b
print('result of a>b',c)
c=a<b
print('result of a<b',c)

result of a==b [False  True  True False]
result of a>b [ True False False  True]
result of a<b [False False False False]


# The any() function can be used to determine if any one element of the array is True.

# The all() function can be used to determine whether all the elements in the array are True.

In [ ]:
from numpy import *
a=array([1,2,3,5,0])
print(any(a))
print(all(a))

True
False


In [ ]:
from numpy import *
a=array([0,0,0,0,0])
print(any(a))
print(all(a))

False
False


In [ ]:
from numpy import *
a=array([1,2,3,4,5])
print(any(a))
print(all(a))

True
True


In [ ]:
from numpy import*
a=array([1,2,3,4])
b=array([0,2,3,1])
c=a>b
print('result of a>b',c)
print(any(c))

c=a<b
print('result of a<b',c)
print(any(c))

c=a==b
print('result of a==b',c)
print(any(c))

result of a>b [ True False False  True]
True
result of a<b [False False False False]
False
result of a==b [False  True  True False]
True


# logical functions on arrays

In [ ]:
#logical_and(), logical_or(), logical_not()
from numpy import*
a=array([1,2,3])
b=array([0,2,3])
c=logical_and(a>0,a<4)# applies on every element in array
print(c)
c=logical_or(b>=0,b==1)
print(c)
c=logical_not(b)
print(c)

[ True  True  True]
[ True  True  True]
[ True False False]


# where() function can be used to create a new array based on whether a given condition is True or False.
* syntax\
array=where(condtion, expression1 if True, expression2 if False)



In [ ]:
#example 
from numpy import*
a=array([10,25,30,43,50,54,60])
b=where(a%2==0,a,0) # condtion applies on every element
print(b)

[10  0 30  0 50 54 60]


# nonzero() function is useful to know the position of elements which are nonzero.

In [ ]:
#example
from numpy import*
a=array([10,25,30,0,50,54,0])
print(nonzero(a))

(array([0, 1, 2, 4, 5]),)


In [ ]:
#to retrieving nonzero elements
for i in nonzero(a):
  print(a[i])

[10 25 30 50 54]


# Aliasing array()
if a is an array, we can assign it to b as b =a.\
it means b is not a new array and memory is not allocated to b.\
also elements of a are not copied into b since there is no memory for b.
aliasing means giving another name to the existing array.Hence any modification to the alias array will reflect in the existing array and vice versa.





In [ ]:
#example
from numpy import*
a=array([1,2,3,4,5])
b=a
print('original array',a)
print('aliased array',b)

original array [1 2 3 4 5]
aliased array [1 2 3 4 5]


In [ ]:
b[0]=55

In [ ]:
print('after modification original array',a)
print('after modification alias array',b)

after modification original array [55  2  3  4  5]
after modification alias array [55  2  3  4  5]


# viewing and copying arrays
* viewing:
viewing can create another array that is same as an existing array. This is done by view method().
If the newly created array is modified, the original array will also be modified.\
Viewing is nothing but copying only. It is called shallow copying as the elements in the view when modified will also modify the elements in the original array.

In [ ]:
#example for view()
from numpy import *
a=arange(1,6)
b=a.view()
print('original array',a)
print('new array',b)

original array [1 2 3 4 5]
new array [1 2 3 4 5]


In [ ]:
b[0]=90

In [ ]:
print('original after modificaiton',a)
print('new array after modificaion',b)

original after modificaiton [90  2  3  4  5]
new array after modificaion [90  2  3  4  5]


# copy() method
If we want both the arrays to be independent and modifying one array should not affect another array, we should go for 'deep copying'. This is done by using copy() method.

In [ ]:
# example for deep copying
from numpy import *
a=arange(1,6)
b=a.copy()
print('original array',a)
print('new array',b)

b[1]=22

print('original after modif',a)
print('new array afte modif',b)

original array [1 2 3 4 5]
new array [1 2 3 4 5]
original after modif [1 2 3 4 5]
new array afte modif [ 1 22  3  4  5]


# Slicing In numpy arrays:


In [ ]:
from numpy import*
a=arange(1,20)
print(a[5:9])

[6 7 8 9]


In [ ]:
print(a[1:15:2])

[ 2  4  6  8 10 12 14]


In [ ]:
print(a[1:15:-1])

[]


In [ ]:
print(a[-1:-15:-1])

[19 18 17 16 15 14 13 12 11 10  9  8  7  6]


In [ ]:
print(a[-1:-15:1])

[]


In [ ]:
print(a[-15:-1:1])

[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18]


# Dimensions of Arrays

In [ ]:
#example for one dimensional(1D) arrays
arr1=array([1,2,3,4,5]) #row vector 
print(arr1)

[1 2 3 4 5]


In [ ]:
arr2=array([1,
            2,
            3,
            4]) #array with column
print(arr2)

[1 2 3 4]


In [ ]:
#example for 2D arrays which are combination of 1D arrays
arr=array([[1,2,3,4],
          [4,5,6,7],
          [8,9,10,11]])
print(arr)

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In the above example each row represents 1D array

similarly we can imagine 3D array is combination of several 2D arrays

In [ ]:
# example for 3D arrays
arr3=array([[[1,2,3],[4,5,6]],
           [[7,8,9],[10,11,12]],
            [[1,2,3],[4,5,6]]])
print(arr3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[ 1  2  3]
  [ 4  5  6]]]


# Attributes of an array

Numpy's array class is called ndarray. It is also known by alias name array.

There is another class array in python that is different from the numpy's array class.

# ndim
represents number of dimensions


In [ ]:
arr1=array([1,2,3,4,5])
print(arr1.ndim)

1


In [ ]:
arr3=array([[[1,2,3],[4,5,6]],
           [[7,8,9],[10,11,12]],
            [[1,2,3],[4,5,6]]])
print(arr3.ndim)

3


# shape
gives the shape of the array, for 1D it gives the number of elements 

for nD it gives the number of rows and coloumns


In [ ]:
arr1=array([1,2,3,4,5])
print(arr1.shape)

(5,)


In [ ]:
#for 2D array
arr=array([[1,2,3,4],
          [4,5,6,7],
          [8,9,10,11]])
print(arr.shape)

(3, 4)


In [ ]:
#for 3D array
arr3=array([[[1,2,3,1],[4,5,6,4]],
           [[7,8,9,7],[10,11,12,10]],
            [[1,2,3,1],[4,5,6,4]]])
print(arr3.shape)

(3, 2, 4)


In [ ]:
#we can change the shape of the array

arr3.shape=(2,2,6)
print(arr3)

[[[ 1  2  3  1  4  5]
  [ 6  4  7  8  9  7]]

 [[10 11 12 10  1  2]
  [ 3  1  4  5  6  4]]]


# Size
gives total number of elements in array

In [ ]:
print(arr3.size)

24


# itemsize
gives the memory size of the array element in bytes.


In [ ]:
print(arr3.itemsize)

8


In [ ]:
from numpy import*
arr1=array([2,3,4])
print(arr1.itemsize)

8


# dtype
gives the datatype of the elements in the array.


In [ ]:
print(arr1.dtype)

int64


In [ ]:
arr=array([1.2,4.6,2.3,1])
print(arr.dtype)

float64


#nbytes
gives the total number of bytes occupied by an array.\
number of bytes= size of the array * item size of each element in the array

In [ ]:
print(arr.itemsize)
print(arr.size)
print(arr.nbytes)

8
4
32


# reshape() method
it is useful to change the shape of array.


In [ ]:
arr=arange(10)
print(arr)
print('after reshape')
arr2=arr.reshape(2,5)
print(arr2)

[0 1 2 3 4 5 6 7 8 9]
after reshape
[[0 1 2 3 4]
 [5 6 7 8 9]]


# flatten() method
 returns a copy of the array collapsed into one dimension.

In [ ]:
arr3=array([[[1,2,3,1],[4,5,6,4]],
           [[7,8,9,7],[10,11,12,10]],
            [[1,2,3,1],[4,5,6,4]]])

arr4=arr3.flatten()
print(arr4)

[ 1  2  3  1  4  5  6  4  7  8  9  7 10 11 12 10  1  2  3  1  4  5  6  4]


# Working with multi-dimensional arrays
* using array() function
* using ones() and zeros()
* using eye() function
* using reshape() function

In [ ]:
#using array() function
from numpy import*
a=array([1,2,3,4]) # 1D
b=array([[2,3,4],[6,7,8]]) # 2D

print(a)
print()
print(b)

[1 2 3 4]

[[2 3 4]
 [6 7 8]]


In [ ]:
#using ones()
#ones((rows,columns),dtype))
ones((3,3),int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
ones((3,3),float)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
#using zeros() function
#zeros((rows,columns),dtype)
zeros((2,3),int)

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
#using eye() function, create ndim array with diagonal elements as 1's.
#eye(n,dtype=datatype)
eye(3,dtype=int)


array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [ ]:
eye(3,dtype=float)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
eye(1,dtype=float)

array([[1.]])

In [ ]:
#using reshape() function
#reshape(arr,(n,r,c)), n arrays with r rows and c columns

a=arange(1,21)
print(a)
b=reshape(a,(2,2,5))
print(b)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]


# Indexing in Multi-dimensional Arrays

In [ ]:
from numpy import *
a=array([[1,2,3],
          [4,5,6],
          [7,8,9]])
print(a)
print()
for i in range(len(a)):
  print('row',i,a[i])

[[1 2 3]
 [4 5 6]
 [7 8 9]]

row 0 [1 2 3]
row 1 [4 5 6]
row 2 [7 8 9]


In [ ]:
for i in range(len(a)):
  for j in range(len(a[i])):
    print('row',i,'colum',j,'is',a[i][j])

row 0 colum 0 is 1
row 0 colum 1 is 2
row 0 colum 2 is 3
row 1 colum 0 is 4
row 1 colum 1 is 5
row 1 colum 2 is 6
row 2 colum 0 is 7
row 2 colum 1 is 8
row 2 colum 2 is 9


In [ ]:
# 3D array
from numpy import *
#create 3D array with size 2x2x3
a=array([[[1,2,3],[1,2,3]],
         [[4,5,6],[7,8,9]]])
print(a.ndim)

3


In [ ]:
for i in range(len(a)):
  for j in range(len(a[i])):
    for k in range(len(a[i][j])):
      print(a[i][j][k],end=' ')
    print()
  print()

1 2 3 
1 2 3 

4 5 6 
7 8 9 



# slicing with multi-dimensional array


In [ ]:
from numpy import*
a=array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
a[:,:] #this will  display the entire 2D array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a[:] # this will  display the entire 2D array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a[: :]# this will display the entire 2D array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a[0,:] # 0 represents row number, : represents all column elements in that row

array([1, 2, 3])

In [ ]:
a[:,0] #  returns all the rows of 0th column

array([1, 4, 7])

In [ ]:
a[:,1]# all the rows of 1st column

array([2, 5, 8])

In [ ]:
a[:,2]# all the rows of 2nd column

array([3, 6, 9])

In [ ]:
a[0:1,0:1] #first row, first column

array([[1]])

In [ ]:
a[1:2,1:2]# 1st row, 1st column

array([[5]])

In [ ]:
a[2:3,1:2] # 2nd row and 1st column

array([[8]])

# Matrices in numpy

what is matrix?.

matrix represents a rectangular array of elements arranged in rows and columns.

* row matrix:\
if a matrix has 1 row, it is called a 'row matrix'.
* column matrix:\
if a matrix has 1 column, it is called a 'column matrix'.

# To work with numpy matrices, numpy provides a special object called **matrix**.

In [ ]:
from numpy import *
arr=array([[1,2,3],[4,5,6],[7,8,9]])
print(type(a))
A=matrix(arr)
print(type(A))

<class 'numpy.ndarray'>
<class 'numpy.matrix'>


In [ ]:
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#we can also pass 2D array directly to matrix object as:
B=matrix([[1,4,3],[4,5,6],[5,6,7]])
print(B)

[[1 4 3]
 [4 5 6]
 [5 6 7]]


In [ ]:
B

matrix([[1, 4, 3],
        [4, 5, 6],
        [5, 6, 7]])

In [ ]:
# we can also pass string of elements 
str1='1 2 3;4 5 6;7 8 9' # semicolon is there after each row of elements
b=matrix(str1)
b

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
c=matrix('1 2 3;4 5 6;7 8 9')
c

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

# Getting diagonal elements of matrix

using diagonal() function

In [ ]:
d=diagonal(c)
d

array([1, 5, 9])

In [ ]:
print(d)

[1 5 9]


# finding maximum and minimun elements

using max() and min() methods

In [ ]:
big=c.max()
print('max is',big)
small=c.min()
print('min is',small)

max is 9
min is 1


# finding sum and average of elements in matrix

using sum() and mean() methods

In [ ]:
print('sum of elements',c.sum())
print('average of elements',c.mean())

sum of elements 45
average of elements 5.0


#product of Elements

using prod() method

In [ ]:
m=matrix(arange(1,13).reshape(3,4))
m

matrix([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [ ]:
print('product of column elements:',m.prod(0))# 0 represents product of column elements

product of elements: [[ 45 120 231 384]]


In [ ]:
print('product of row elements:',m.prod(1))# 1 represents product of row elements

product of elements: [[   24]
 [ 1680]
 [11880]]


In [ ]:
print('product of all elements',m.prod())

product of all elements 479001600


# sorting the matrix

using sort() function
* syntax:\
sort(matrix,axis) axis=0 represents colum wise sort,1 for row wise, by default sorted row wise.

In [ ]:
m=matrix([[5,4,1],[2,7,0]])
m

matrix([[5, 4, 1],
        [2, 7, 0]])

In [ ]:
print(sort(m))# defualt sorted row wise

[[1 4 5]
 [0 2 7]]


In [ ]:
print(sort(m,axis=1)) # 1 represents row wise sorted

[[1 4 5]
 [0 2 7]]


In [ ]:
print(sort(m,axis=0))# column wise sorted

[[2 4 0]
 [5 7 1]]


# Transpose of matrix
using tranpose() and getT() methods

In [ ]:
t=m.transpose()
print('before transpose:')
print(m)
print('after transpose')
print(t)

before transpose:
[[5 4 1]
 [2 7 0]]
after transpose
[[5 2]
 [4 7]
 [1 0]]


In [ ]:
#using getT() method
t1=m.getT()
print('before transpose')
print(m)
print('after transpose')
print(t1)

before transpose
[[5 4 1]
 [2 7 0]]
after transpose
[[5 2]
 [4 7]
 [1 0]]


In [ ]:
# write a python program to accept a matrix from the keyboard and display transpose matrix
from numpy import*
# accept number of rows and columns into r,c
r,c=[int(a) for a in input('enter rows, cols:').split()]
# accept the matrix elements as a string into str
st1=input('enter the matrix elements:')
#convert the string into matrix with size rXc
x=reshape(matrix(st1),(r,c))
print('orignal matrix')
print(x)
print()
print('transposed matrix')
y=x.transpose()
print(y)

enter rows, cols:3 3
enter the matrix elements:1 2 3 4 5 6 7 8 9
orignal matrix
[[1 2 3]
 [4 5 6]
 [7 8 9]]

transposed matrix
[[1 4 7]
 [2 5 8]
 [3 6 9]]


# matrix addition and multiplication


In [ ]:
from numpy import*
A=matrix(arange(1,10).reshape(3,3))
B=matrix(arange(4,13).reshape(3,3))
print('matrix A is\n',A)
print('matrix B is\n',B)

matrix A is
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
matrix B is
 [[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
# addition
print(A+B)# corresponding elements are added

[[ 5  7  9]
 [11 13 15]
 [17 19 21]]


In [ ]:
# substraction
print(A-B)# corresponding elements are substracted

[[-3 -3 -3]
 [-3 -3 -3]
 [-3 -3 -3]]


In [ ]:
#division
print(A/B) #corresponding elements are divided.

[[0.25       0.4        0.5       ]
 [0.57142857 0.625      0.66666667]
 [0.7        0.72727273 0.75      ]]


In [ ]:
from numpy import*
A=matrix(arange(1,11).reshape(2,5))
B=matrix(arange(4,13).reshape(3,3))
print('matrix A is\n',A)
print('matrix B is\n',B)

matrix A is
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
matrix B is
 [[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
print(A+B) # cannot perform add, sub, div because matrix size is not same

ValueError: ignored

#Matrix Multiplication

If we want to perform matrix multiplicaton between A and B.
the number of columns in matrix A is equal to number of rows in matrix B.


In [ ]:
from numpy import*
A=matrix(arange(1,10).reshape(3,3))
B=matrix(arange(4,13).reshape(3,3))
print('matrix A is\n',A)
print('matrix B is\n',B)

matrix A is
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
matrix B is
 [[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
print('product of two matrices A and B is\n',A*B)

product of two matrices A and B is
 [[ 48  54  60]
 [111 126 141]
 [174 198 222]]


# Random numbers
using random is a moudule in numpy


In [ ]:
random.rand()

0.9480478533031536

In [ ]:
random.rand(5)

array([0.41883434, 0.80322005, 0.92109171, 0.66433804, 0.69410029])

In [ ]:
random.rand(2,4)

array([[0.46490704, 0.45940492, 0.97673711, 0.96213842],
       [0.48516573, 0.16015651, 0.98114865, 0.9922096 ]])